apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gwc2byary-nodejs
  janus-idp.io/tekton: gwc2byary-nodejs
  backstage.io/kubernetes-id: gwc2byary-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gwc2byary-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
