apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: gwc2byary-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gwc2byary-nodejs 
  name: gwc2byary-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: gwc2byary-nodejs 
